### ISSUE TITLE
Add E-Mail Headers

### ISSUE THREAD

**Issue by HaNdTriX** [jasonbellamy/react-mailto#2]
I would be really nice to allow setting email headers such as `cc, body, subject` etc.

> In addition to the email address, you can provide other information. In fact, any standard mail header fields can be added to the mailto URL you provide. The most commonly-used of these are "subject", "cc", and "body" (which is not a true header field, but allows you to specify a short content message for the new email). Each field and its value is specified as a query term.

https://developer.mozilla.org/de/docs/Web/Guide/HTML/Email_links
https://tools.ietf.org/html/rfc2368

## Example

    mailto:email@example.com?Subject=react-mailto%20needs%20header&cc=cc%40example.com&bcc=bcc%40example.com&body=This%20is%20just%20an%20example.%20%0AThere%20a%20lot%20more%20headers%20that%20could%20be%20added.

**[Try Me!](mailto:email@example.com?Subject=react-mailto%20needs%20header&cc=cc%40example.com&bcc=bcc%40example.com&body=This%20is%20just%20an%20example.%20%0AThere%20a%20lot%20more%20headers%20that%20could%20be%20added.)**

## Integration

I suggest to add an headers property.

    <Mailto 
      email="j@sonbellamy.com" 
      headers={{
        bcc: 'bcc@example.de',
        cc: 'bcc@example.de',
        subject: 'someSubject',
        body: 'some body',
        ...
      }}>
      Email me!
    </Mailto>

**Comment by jasonbellamy** [comment]
I think this is a great idea @HaNdTriX  I can probably find some time over the next couple of days to add this in (the code could probably use some cleanup anyways), otherwise feel free to open up PR if like. :)
